# Generated by Django 5.0.6 on 2024-05-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_client_event_seat_ticket_ticket_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default='2024-05-20'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2024-05-20'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
