# Generated by Django 5.0.6 on 2024-05-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(max_length=300, upload_to='images/'),
        ),
    ]
