# Generated by Django 5.0.6 on 2024-05-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_client_name_remove_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about_text',
            field=models.CharField(max_length=500),
        ),
    ]
